
# op map for nova.
op_map = \
{(8776, '/v2', '/extensions', 'GET', ''): (),
 (8776, '/v2', '/os-availability-zone', 'GET', ''): (),
 (8776, '/v2', '/os-hosts', 'GET', ''): ('volume_extension:hosts',),
 (8776, '/v2', '/os-quota-sets/%ID%', 'DELETE', ''): ('volume_extension:quotas:delete',),
 (8776, '/v2', '/os-quota-sets/%ID%', 'GET', ''): ('volume_extension:quotas:show',),
 (8776, '/v2', '/os-quota-sets/%ID%', 'PUT', ''): ('volume_extension:quotas:update',),
 (8776, '/v2', '/os-quota-sets/%ID%/defaults', 'GET', ''): ('volume_extension:quotas:show',),
 (8776, '/v2', '/os-services', 'GET', ''): ('volume_extension:services',),
 (8776, '/v2', '/os-services?binary=%VALUE%', 'GET', ''): ('volume_extension:services',),
 (8776, '/v2', '/os-services?binary=%VALUE%&host=%VALUE%', 'GET', ''): ('volume_extension:services',),
 (8776, '/v2', '/os-services?host=%VALUE%', 'GET', ''): ('volume_extension:services',),
 (8776, '/v2', '/qos-specs', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs', 'POST', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%', 'DELETE', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%', 'PUT', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%/associate?vol_type_id=%VALUE%', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%/associations', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%/delete_keys', 'PUT', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%/disassociate?vol_type_id=%VALUE%', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/qos-specs/%UUID%/disassociate_all', 'GET', ''): ('volume_extension:qos_specs_manage',),
 (8776, '/v2', '/snapshots', 'POST', ''): (),
 (8776, '/v2', '/types', 'GET', ''): ('volume_extension:volume_type_access',),
 (8776, '/v2', '/types', 'POST', ''): ('volume_extension:types_manage',
                                       'volume_extension:volume_type_access'),
 (8776, '/v2', '/types/%UUID%', 'DELETE', ''): ('volume_extension:types_manage',),
 (8776, '/v2', '/types/%UUID%', 'GET', ''): (),
 (8776, '/v2', '/types/%UUID%/encryption', 'GET', ''): ('volume_extension:volume_type_encryption',),
 (8776, '/v2', '/types/%UUID%/encryption', 'POST', ''): ('volume_extension:volume_type_encryption',),
 (8776, '/v2', '/types/%UUID%/encryption/provider', 'DELETE', ''): ('volume_extension:volume_type_encryption',),
 (8776, '/v2', '/types/%UUID%/extra_specs', 'GET', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/types/%UUID%/extra_specs', 'POST', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/types/%UUID%/extra_specs/%NAME%', 'DELETE', ''): (),
 (8776, '/v2', '/types/%UUID%/extra_specs/%NAME%', 'GET', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/types/%UUID%/extra_specs/%NAME%', 'PUT', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/types/%UUID%/extra_specs/%UUID%', 'GET', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/types/%UUID%/extra_specs/%UUID%', 'PUT', ''): ('volume_extension:types_extra_specs',),
 (8776, '/v2', '/volumes', 'POST', ''): ('volume:create',)}
