
# op map for glance.
op_map = \
{(9292, '/v1', '/images', 'DELETE', ''): (),
 (9292, '/v1', '/images', 'POST', ''): (),
 (9292, '/v1', '/images/%NAME%', 'DELETE', ''): ('delete_image',),
 (9292, '/v1', '/images/%UUID%', 'DELETE', ''): ('delete_image',),
 (9292, '/v1', '/images/%UUID%', 'GET', ''): ('get_image', 'download_image'),
 (9292, '/v1', '/images/%UUID%', 'HEAD', ''): ('get_image',),
 (9292, '/v1', '/images/%UUID%/members/%ID%', 'DELETE', ''): ('delete_member',),
 (9292, '/v1', '/images/%UUID%/members/%ID%', 'PUT', ''): ('modify_member',),
 (9292, '/v2', '/images', 'DELETE', ''): (),
 (9292, '/v2', '/images', 'GET', ''): (),
 (9292, '/v2', '/images', 'POST', ''): ('add_image',),
 (9292, '/v2', '/images/%UUID%', 'DELETE', ''): ('get_image',),
 (9292, '/v2', '/images/%UUID%', 'GET', ''): ('get_image',),
 (9292, '/v2', '/images/%UUID%', 'PATCH', ''): ('get_image', 'modify_image'),
 (9292, '/v2', '/images/%UUID%/members', 'GET', ''): ('get_image',
                                                      'get_members'),
 (9292, '/v2', '/images/%UUID%/members', 'POST', ''): ('get_image',
                                                       'add_member'),
 (9292, '/v2', '/images/%UUID%/members/%ID%', 'DELETE', ''): ('get_image',
                                                              'get_member',
                                                              'delete_member'),
 (9292, '/v2', '/images/%UUID%/members/%ID%', 'GET', ''): ('get_image',
                                                           'get_member'),
 (9292, '/v2', '/images/%UUID%/members/%ID%', 'PUT', ''): ('get_image',
                                                           'get_member'),
 (9292, '/v2', '/images/%UUID%/tags/%NAME%', 'DELETE', ''): ('get_image',),
 (9292, '/v2', '/images/%UUID%/tags/%NAME%', 'PUT', ''): ('get_image',),
 (9292, '/v2', '/images?container_format=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/images?disk_format=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/images?limit=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/images?size=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/images?status=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/images?visibility=%VALUE%', 'GET', ''): ('get_images',),
 (9292, '/v2', '/metadefs/namespaces', 'POST', ''): ('add_metadef_namespace',
                                                     'add_metadef_resource_type_association'),
 (9292, '/v2', '/metadefs/namespaces/%NAME%', 'DELETE', ''): ('get_metadef_namespace',),
 (9292, '/v2', '/metadefs/namespaces/%NAME%', 'GET', ''): ('get_metadef_namespace',),
 (9292, '/v2', '/metadefs/namespaces/%NAME%', 'PUT', ''): ('get_metadef_namespace',
                                                           'modify_metadef_namespace'),
 (9292, '/v2', '/metadefs/resource_types', 'GET', ''): ('list_metadef_resource_types',),
 (9292, '/v2', '/schemas/image', 'GET', ''): (),
 (9292, '/v2', '/schemas/images', 'GET', ''): (),
 (9292, '/v2', '/schemas/member', 'GET', ''): (),
 (9292, '/v2', '/schemas/members', 'GET', ''): ()}
